### PR TITLE
[Bug Fix] do not redraw progress bar each time on log in non-tty output

### PR DESCRIPTION
**Pull request by robuye**
## Why This Change Is Necessary

Given following code sample:

```
progress = ProgressBar.create(total: 10, format: "%a %e %P% Processed: %c from %C")

list.each do |element|
  if already_indexed_documents.include?(element.id)
    progress.log("Skipping #{element.id} - already indexed")
    next
  end
  progress.log("Processing #{element.id}")

  do_magic(element)
  progress.increment
end

progress.stop
puts
```

When I run it in non-tty terminal it redraws the bar after each log
entry:

```
Progress: |
Skipping 15e5b1e0ea2672ef - already indexed
Progress: |
Skipping 15e5b1dfa3fb93dd - already indexed
Progress: |
Skipping 15e5b1df7fb279f2 - already indexed
Progress: |
Skipping 15e5b1df5b8b5311 - already indexed
Progress: |
Skipping 15e5b1a0ad86bed4 - already indexed
Progress: |
```
## How These Changes Address the Issue

The change does 2 things for non-TTY terminals:
* disable refresh unless bar is stopped
* `log` will not `clear` the line and as a result will not insert
  blank line

A test case has been added and another test has been rewritten to
be more strict (expect exact number of new lines)

## Side Effects Caused By This Change

- [x] This Causes a Breaking Change

Doube new-line before printing full progress bar, see updated test for details. I personally didn't find this to be a deal-breaker.

## Checklist:

- [x] I have run `rubocop` against the codebase
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

Rubocop did return warnings, but not in a code I changed, possibly different gem versions?

### CODE REVIEW

**Comment by jfelchner** [comment]
@robuye thank you!  I'll take a look.  I've been neglecting PR's but I'm going to set aside a day this weekend to catch up on all my repos.  <3

**Comment by robuye** [comment]
Thanks @jfelchner and no rush. Also thank you for all the work you did on this gem, it's great :)

**Comment by jfelchner** [comment]
@robuye ok so I took a look at the PR.  I have both agreements and disagreements with it.

I agree that if you have a non-TTY bar and you call multiple logs on it, it should not redraw the bar, but what I don't agree with, is if you do something which might have an impact on what the bar's display looks like, it _should_ redraw the bar.

So specifically in your test where you're doing:

```ruby
        progressbar.increment
        progressbar.log 'We All Float'
        progressbar.increment
        progressbar.log 'My hovercraft is full of eels'
```

I would expect to see the bar between `We All Float` and `My hovercraft is full of eels`.  Whereas if the test was:

```ruby
        progressbar.increment
        progressbar.log 'We All Float'
        progressbar.log 'My hovercraft is full of eels'
```

I would expect that the bar would be redrawn after `increment` but then you'd see only the log statements.

This may be a harder thing to pull off than I'd like and so I might punt on this.  But let me take a gander and see what I can see.

**Comment by jfelchner** [comment]
@robuye here is my fix:

```ruby
    it 'it can log messages for a non-TTY enabled device without spamming' do
      progressbar = ProgressBar::Base.new(:output        => non_tty_output,
                                          :length        => 20,
                                          :starting_at   => 4,
                                          :total         => 8,
                                          :throttle_rate => 0.0)

      progressbar.increment
      progressbar.log('We All Float')
      progressbar.log('Hey There Georgie!')
      progressbar.increment

      expect(non_tty_output_string).to eql "\n" \
                                           "Progress: |====\n" \
                                           "We All Float\n" \
                                           "Hey There Georgie!\n" \
                                           "Progress: |======"
    end
```

I want to be clear that no one else has mentioned this as an issue, so if this _won't_ fix your problem, let me know.  I don't like having code in that doesn't really serve a need.  _However_ as of the (as yet unreleased) v1.9, you have an alternative option in [passing a custom output class](https://github.com/jfelchner/ruby-progressbar/wiki/Custom-Output-Classes).  In this way you could do everything that you did in your PR, but have it be local to your project.

What say you? 😀

**Comment by robuye** [comment]
Jeff,

I'm away for ~3 weeks, I will get back to you when I return. Sorry I can't
respond properly and thanks for taking the time looking into this!


On Sep 15, 2017 7:31 AM, "Jeff Felchner" <notifications@github.com> wrote:

@robuye <https://github.com/robuye> here is my fix:

    it 'it can log messages for a non-TTY enabled device without spamming' do
      progressbar = ProgressBar::Base.new(:output        => non_tty_output,
                                          :length        => 20,
                                          :starting_at   => 4,
                                          :total         => 8,
                                          :throttle_rate => 0.0)

      progressbar.increment
      progressbar.log('We All Float')
      progressbar.log('Hey There Georgie!')
      progressbar.increment

      expect(non_tty_output_string).to eql "\n" \
                                           "Progress: |====\n" \
                                           "We All Float\n" \
                                           "Hey There Georgie!\n" \
                                           "Progress: |======"
    end

I want to be clear that no one else has mentioned this as an issue, so if
this *won't* fix your problem, let me know. I don't like having code in
that doesn't really serve a need. *However* as of the (as yet unreleased)
v1.9, you have an alternative option in passing a custom output class
<https://github.com/jfelchner/ruby-progressbar/wiki/Custom-Output-Classes>.
In this way you could do everything that you did in your PR, but have it be
local to your project.

What say you? 😀

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jfelchner/ruby-progressbar/pull/137#issuecomment-329685613>,
or mute the thread

**Comment by robuye** [comment]
I'm finally back and can look into it properly.

I see your points about redrawing the bar whenever it could change. I'm happy with your fix or my own Output class if necessary - there is no need to add a complexity if no one else had an issue with it.

That said I tried to run your test, but it failed (the progress bar was drawn between log lines), is it something you didn't push yet?

Thank you very much for taking the time to investigate this!

**Comment by jfelchner** [comment]
@robuye if the output class works for you, I'm going to go ahead and close this.  Thanks for taking the time to submit. ❤

**Pull request closed without merging**
