### PR TITLE
Add Enumerator#to_progressbar

### PR DESCRIPTION
**Pull request by ronen**
This PR contains the Enumerator#to_progressbar method proposed in #124, along with some specs.  

I included `enumerator.rb`  in `progressbar.rb`, so this would be automatically included as part of the gem.  If you'd rather not by default add a method to the global `Enumerator` class, it could be left out of `progressbar.rb` so that users would need to `require 'ruby-progressbar/enumerator'`

### CODE REVIEW

**Comment by ronen** [comment]
Update: `Enumerator#to_progressbar` can only work if `Enumerator` is defined (ruby > 1.8) as well as `Enumerator#size` (ruby > 1.9); this PR has been updated with a guard so that it's a no-op otherwise.

As for the build failing, that seems to be some problem with jruby & bundler -- it gives an error message unrelated to my new code.  I tried adding ruby-core to the Gemfile as per the error message but it made no difference.

**Comment by jfelchner** [comment]
Thanks @ronen I'm on the fence on this so I'm just mulling it over. I definitely won't be including it by default, but I'm wondering if a refinement might be a better option here.

**Comment by ronen** [comment]
@jfelchner Yes I can agree with not including it by default.   

And I've personally not (yet?) joined the refinements bandwagon for the common reasons in my usual coding, but yes I can see that this seems like a reasonable use for a refinement.   So #126 has the refinement version.

**Comment by jfelchner** [comment]
Closing this in favor of #126

**Pull request closed without merging**
