### PR TITLE
Don't calculate the estimated time if timer is reset

### PR DESCRIPTION
**Pull request by bladebhs**
Why This Change Is Necessary
--------------------------------------------------------------------------------

- [X] Bug Fix

It fixes the issue #160  when the bar is incremented after the reset but ETA is still unknown

How These Changes Address the Issue
--------------------------------------------------------------------------------

It doesn't calculate the estimated time if timer is reset

Side Effects Caused By This Change
--------------------------------------------------------------------------------

- [X] This Does Not Cause Any Known Side Effects

Checklist:
--------------------------------------------------------------------------------

- [ ] I have run `rubocop` against the codebase
- [X] I have added tests to cover my changes
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by bladebhs** [comment]
@jfelchner 
Seems CI pipeline is broken for some ruby versions.
Also I'm not able to run Rubocop because it needs `rubocop_rails.yml` config.

**Comment by jfelchner** [comment]
Strange! The PR is good enough and I appreciate it.  I'm going to be working through all my repos this week and getting them back in shape.  I'll work on this PR then.  Thanks again for taking the time to PR this! ❤️

**Comment by jfelchner** [comment]
Merged in d1b09de

Thank you @bladebhs!!! ❤️

**Comment by jfelchner** [comment]
(Also I've converted the repo to Github Actions for CI so you should no longer have the issue you had with the rubocop file)

**Review by stevenans9859 — APPROVED** [review]

**Pull request closed without merging**
